### PR TITLE
Rename methods

### PR DESCRIPTION
**Pull request by Laquin-Laquih**
#### Capitalized terminations:
- `_Alloc`
- `_Compare`
- `_Const_Get`
- `_Copy`
- `_Delete`
- `_Exec`
- `_Exists`
- `_Exit`
- `_Get`
- `_Init`
- `_Init_*` (e.g. `MailMsg_Init_FromTemplate`)
- `_Invalidate`
- `_New`
- `_New_Custom`
- `_Print`
- `_Run`
- `_Set`
- `_Setup`
- ~`_Sizeof`~
- `_Teardown`

#### Renamed terminations:
- `_ctor` to `_New`
- `_dtor` to `_Delete`

#### Other renamed functions:
- `WM_sp_init` to `WMSP_Init` and `__VENEER_WM_sp_init` to `__VENEER_WMSP_Init`
- made `bag_view` functions PascalCase
- fixed style for functions in `pm_string.h`
- capitalized functions in`sound_chatot.h`

#### Excluded files:
- `tools/*`
- `lib/*`
- `.github/*`
- `*.gmm,`
- `nitrocrypto.s`

### CODE REVIEW

**Review by red031000 — CHANGES_REQUESTED** [review]
only things I would suggest is keeping sizeof lowercase, and changing C_Str to cstr (also lowercase) as these are defined in the c standard library as such

**Comment by red031000** [comment]
another debate is with Narc_ctor and Narc_dtor, about whether they should be Narc_Open and Narc_Close respectively

**Comment by Laquin-Laquih** [comment]
> only things I would suggest is keeping sizeof lowercase, and changing C_Str to cstr (also lowercase) as these are defined in the c standard library as such

Alright!, that's what I imagined. Should `String_atoi` be lowercase as well, for the same reason?

> another debate is with Narc_ctor and Narc_dtor, about whether they should be Narc_Open and Narc_Close respectively

Hmmm yeah, that could work as well. To be fair, the function does create a _new_ NARC object, which acts as a kind of interface to access a FSFile from what I understand, so you technically are opening the FSFile and creating a NARC. (?) But from the user's perspective, it may well be easier to understand what the function is used for if it's named `_Open`...

**Comment by red031000** [comment]
probably a good idea for atoi

as for new vs open there is a debate to be had for that one

**Comment by Laquin-Laquih** [comment]
rebased branch to avoid conflicts when merging

**Review by red031000 — APPROVED** [review]

**Pull request merged**
